eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.68.62:8089/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: firstservice
        uri: lb://first-service
        predicates:
        - Path=/api/first-service/**
        filters:
        - RewritePath=/api/first-service/(?<segment>.*), /$\{segment}
      - id: secondservice
        uri: lb://second-service
        predicates:
        - Path=/api/second-service/**
        filters:
        - name: CircuitBreaker 
        - RewritePath=/api/second-service/(?<segment>.*), /$\{segment}
